version: 2.1
description: "Static Site Starter Orb"

display:
  source_url: https://github.com/devheart/static-site-starter-orb

commands:
  install:
    description: "Install dependencies"
    steps:
      - bundle_install
      - yarn_install

  yarn_install:
    description: "Install yarn dependencies"
    steps:
      - restore_cache:
          name: "[sss] yarn/restore_cache"
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-
      - run:
          name: "[sss] yarn/install"
          command: yarn install --frozen-lockfile
      - save_cache:
          name: "[sss] yarn/save_cache"
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  bundle_install:
    description: "Install bundles"
    steps:
      - run:
          name: "[sss] bundles/update_bundler"
          command: |
            echo "gem: --no-rdoc --no-ri" >> jekyll/.gemrc
            echo "gem: --no-document" >> jekyll/.gemrc
            gem install bundler
            sudo chown -R circleci /usr/local/bundle
            bundler --version
      - restore_cache:
          name: "[sss] bundles/restore_cache"
          keys:
            - bundles-{{ checksum "jekyll/Gemfile.lock" }}
            - bundles-
      - run:
          name: "[sss] bundles/install"
          command: cd jekyll && bundle install
      - save_cache:
          name: "[sss] bundles/save_cache"
          paths:
            - /usr/local/bundle
          key: bundles-{{ checksum "jekyll/Gemfile.lock" }}

  build:
    description: "Build"
    steps:
      - run:
          name: "[sss] build"
          command: yarn build

  firebase_deploy:
    description: "Deploy to Firebase"
    parameters:
      project_id:
        type: string
      token:
        type: string
    steps:
      - run:
          name: "[sss] firebase/deploy"
          command: |
            yarn add firebase-tools --frozen-lockfile
            ./node_modules/.bin/firebase deploy --non-interactive --project "<< parameters.project_id >>" --token "<< parameters.token >>"

jobs:
  build_and_deploy:
    docker:
      - image: circleci/ruby:2.7-node
    environment:
      JEKYLL_ENV: production
    steps:
      - checkout
      - install
      - build
      - firebase_deploy:
          project_id: $FIREBASE_PROJECT_ID
          token: $FIREBASE_TOKEN
